# Generated by Django 2.2.7 on 2020-07-25 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companydetails',
            fields=[
                ('CompanyName', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('GST', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('ProductName', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('Cost', models.FloatField(default=None)),
                ('CompanyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Companydetails')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.CharField(default=None, max_length=100, null=True)),
                ('Quantity', models.FloatField(default=None)),
                ('Rate', models.FloatField(default=None)),
                ('Total', models.FloatField(default=None)),
                ('CompanyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Companydetails')),
                ('ProductName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.ProductDetails')),
            ],
        ),
    ]
